import type { RagConfigFormState } from "./PrudentiaSettingsPage";

export const ollamaForm: RagConfigFormState = {
  provider: "ollama",
  embedding_provider: "ollama",
  reasoning_provider: "ollama",
  routing_provider: "ollama",
  faithfulness_provider: "ollama",
  ingestion_provider: "ollama",
  vision_provider: "ollama",
  inference_location: "local",
  host: "",
  port: "11434",
  embedding_host: "",
  embedding_port: "11434",
  reasoning_host: "",
  reasoning_port: "11434",
  routing_host: "",
  routing_port: "11434",
  faithfulness_host: "",
  faithfulness_port: "11434",
  ingestion_host: "",
  ingestion_port: "11434",
  vision_host: "",
  vision_port: "11434",
  chat_model: "llama3.1:8b",
  embed_model: "nomic-embed-text:latest",
  reasoning_model: "",
  routing_model: "",
  faithfulness_model: "",
  ingestion_model: "",
  vision_model: "",
  reranker_model: "jinaai/jina-reranker-v1-turbo-en",
  thinking_enabled: true,
  query_planner_enabled: true,
  json_num_predict: "4096",
  retrieval_token_budget: "12000",
  chat_timeout_seconds: "180",
  embed_timeout_seconds: "45",
};
