import type { ReviewItem } from "@/types/api";

export function devReviewPreviewItems(): ReviewItem[] | null {
  if (!import.meta.env.DEV) return null;
  if (new URLSearchParams(window.location.search).get("preview") !== "ocr-items") return null;
  return [
    {
      id: "preview-review-1",
      assigned_to: "OCR reviewer",
      batch_id: "preview-batch-1",
      bbox: [82, 156, 486, 218],
      confidence: 0.43,
      corrected_text: null,
      created_at: "2026-06-18T09:00:00Z",
      doc_id: "preview-doc-fir",
      doc_title: "FIR Intake Packet 042.pdf",
      item_index: 7,
      item_type: "text_block",
      page_end: 3,
      page_start: 3,
      partial_text: "Accused name appears as Sajjad Husan; CNIC value unclear near the final two digits.",
      quality_flags: ["source:ocr", "low_confidence", "name_entity_uncertain"],
      status: "pending",
      updated_at: null,
    },
    {
      id: "preview-review-2",
      assigned_to: null,
      batch_id: "preview-batch-1",
      bbox: [96, 312, 510, 374],
      confidence: 0.58,
      corrected_text: "Vehicle registration LED-4821; incident time 22:40.",
      created_at: "2026-06-18T09:02:00Z",
      doc_id: "preview-doc-fir",
      doc_title: "FIR Intake Packet 042.pdf",
      item_index: 8,
      item_type: "table_row",
      page_end: 4,
      page_start: 4,
      partial_text: "Vehicle registration LEO-482?; incident time 22:4O.",
      quality_flags: ["source:ocr", "table_alignment", "numeric_ambiguity"],
      status: "pending",
      updated_at: null,
    },
    {
      id: "preview-review-3",
      assigned_to: "OCR reviewer",
      batch_id: "preview-batch-2",
      bbox: null,
      confidence: null,
      corrected_text: null,
      created_at: "2026-06-18T09:04:00Z",
      doc_id: "preview-doc-statement",
      doc_title: "Witness Statement Scan.pdf",
      item_index: 2,
      item_type: "paragraph",
      page_end: 1,
      page_start: 1,
      partial_text: "Statement contains handwritten location details; page highlight unavailable.",
      quality_flags: ["source:ocr", "missing_bbox", "handwriting"],
      status: "pending",
      updated_at: null,
    },
  ];
}
