import type { FormEvent } from "react";
import type { RouteId } from "@/routes/routes";
import type { Document, QuerySourceMode, SourceAnchor, User as AuthUser } from "@/types/api";
import type { ChatTurn, SavedChatSessionSummary } from "@/types/chat";

export type Props = {
  activeSessionId: string | null;
  activeSpacePath: string | null;
  activeSessionHasPendingTurn: boolean;
  addScopedDocument: (documentId: string) => void;
  cancelPendingTurn: () => void;
  chatTurns: ChatTurn[];
  currentDocuments: Document[];
  deleteChatSession: (sessionId: string) => void;
  documents: Document[];
  documentsLoading: boolean;
  generatingSessionId: string | null;
  hasPendingGeneration: boolean;
  latestResponse: { sources: SourceAnchor[] } | null;
  loadChatSession: (sessionId: string) => void;
  loadMoreSavedSessions: () => void;
  loadingSessionId: string | null;
  onLogout: () => void;
  onActiveSpaceChange: (groupPath: string | null) => void;
  onCancelArtifactJob: (jobId: string) => Promise<void>;
  onClarifyArtifactJob: (jobId: string, answers: Record<string, string>) => Promise<void>;
  onExpandSourceSearch: (assistantTurnId: string) => void;
  onNavigate: (route: RouteId) => void;
  onQuestionChange: (value: string) => void;
  onQuestionSubmit: (event: FormEvent<HTMLFormElement>) => void;
  onReset: () => void;
  onRetryArtifactJob: (jobId: string) => Promise<void>;
  onSelectedQuerySourceChange: (sourceId: string) => void;
  onSelectSource: (source: SourceAnchor | null) => void;
  onSourceModeChange: (mode: QuerySourceMode) => void;
  question: string;
  removeScopedDocument: (documentId: string) => void;
  savedSessions: SavedChatSessionSummary[];
  savedSessionsError: string | null;
  savedSessionLoadError: string | null;
  savedSessionsFetchingMore: boolean;
  savedSessionsHasMore: boolean;
  savedSessionsLoading: boolean;
  savedSessionsTotal: number;
  scopedDocumentIds: string[];
  selectedQuerySourceId: string;
  selectedSource: SourceAnchor | null;
  sourceMode: QuerySourceMode;
  user: AuthUser;
};
