"""Compatibility collection facade for artifact-generation optimization tests.

The cases live in responsibility-focused modules. Re-exporting them here preserves
the established pytest node IDs used by targeted CI and developer workflows.
"""

from generation_service_cases import (
    test_stage_timing_serializer_handles_missing_and_partial_timings as test_stage_timing_serializer_handles_missing_and_partial_timings,
)
from generation_service_cases import (
    test_artifact_job_summary_exposes_user_facing_progress as test_artifact_job_summary_exposes_user_facing_progress,
)
from generation_service_cases import (
    test_retry_resets_artifact_job_attempt_timestamps as test_retry_resets_artifact_job_attempt_timestamps,
)
from generation_composition_cases import (
    test_composer_truncates_evidence_payload_for_llm_prompt as test_composer_truncates_evidence_payload_for_llm_prompt,
)
from generation_composition_cases import (
    test_composer_failure_falls_back_with_evidence_ids_preserved as test_composer_failure_falls_back_with_evidence_ids_preserved,
)
from generation_composition_cases import (
    test_bundle_evidence_normalization_repairs_missing_ev_prefix as test_bundle_evidence_normalization_repairs_missing_ev_prefix,
)
from generation_composition_cases import (
    test_composer_failure_builds_concise_grouped_table as test_composer_failure_builds_concise_grouped_table,
)
from generation_composition_cases import (
    test_composer_lets_llm_choose_table_structure as test_composer_lets_llm_choose_table_structure,
)
from generation_composition_cases import (
    test_formatter_llm_chooses_presentation_title_subtitle_and_slides as test_formatter_llm_chooses_presentation_title_subtitle_and_slides,
)
from generation_planning_cases import (
    test_planner_extracts_topic_from_detailed_presentation_request as test_planner_extracts_topic_from_detailed_presentation_request,
)
from generation_planning_cases import (
    test_planner_keeps_simple_request_on_fast_path as test_planner_keeps_simple_request_on_fast_path,
)
from generation_planning_cases import (
    test_planner_uses_single_llm_call_for_complex_artifact_request as test_planner_uses_single_llm_call_for_complex_artifact_request,
)
from generation_planning_cases import (
    test_planner_falls_back_when_complex_llm_plan_fails as test_planner_falls_back_when_complex_llm_plan_fails,
)
from generation_planning_cases import (
    test_planner_falls_back_when_generation_provider_is_unavailable as test_planner_falls_back_when_generation_provider_is_unavailable,
)
from generation_composition_cases import (
    test_composer_falls_back_when_generation_provider_is_unavailable as test_composer_falls_back_when_generation_provider_is_unavailable,
)
from generation_planning_cases import (
    test_planner_propagates_soft_time_limit as test_planner_propagates_soft_time_limit,
)
from generation_planning_cases import (
    test_planner_does_not_hide_generator_programming_errors as test_planner_does_not_hide_generator_programming_errors,
)
from generation_composition_cases import (
    test_formatter_propagates_soft_time_limit as test_formatter_propagates_soft_time_limit,
)
from generation_composition_cases import (
    test_section_composition_propagates_soft_time_limit as test_section_composition_propagates_soft_time_limit,
)
from generation_retrieval_cases import (
    test_retrieval_infers_document_family_scope as test_retrieval_infers_document_family_scope,
)
from generation_retrieval_cases import (
    test_retrieval_infers_policy_scope_from_doc_type as test_retrieval_infers_policy_scope_from_doc_type,
)
from generation_retrieval_cases import (
    test_retrieval_does_not_scan_every_structured_row_without_scope as test_retrieval_does_not_scan_every_structured_row_without_scope,
)
from generation_execution_cases import (
    test_seeded_response_job_renders_without_artifact_composition as test_seeded_response_job_renders_without_artifact_composition,
)
from generation_execution_cases import (
    test_seeded_response_job_normalizes_recoverable_evidence_ids as test_seeded_response_job_normalizes_recoverable_evidence_ids,
)
from generation_execution_cases import (
    test_seeded_response_job_falls_back_when_repair_json_is_malformed as test_seeded_response_job_falls_back_when_repair_json_is_malformed,
)
from generation_execution_cases import (
    test_seeded_response_job_uses_deterministic_repair_before_llm as test_seeded_response_job_uses_deterministic_repair_before_llm,
)
from generation_progress_cases import (
    test_composer_reports_progress_for_each_composition_batch as test_composer_reports_progress_for_each_composition_batch,
)
from generation_progress_cases import (
    test_executor_maps_composition_progress_to_visible_job_stages as test_executor_maps_composition_progress_to_visible_job_stages,
)
from generation_progress_cases import (
    test_executor_records_render_format_progress as test_executor_records_render_format_progress,
)
from generation_progress_cases import (
    test_artifact_job_renderer_uses_shared_renderer_for_all_formats as test_artifact_job_renderer_uses_shared_renderer_for_all_formats,
)
from generation_document_rendering_cases import (
    test_deterministic_pdf_renders_polished_primitives as test_deterministic_pdf_renders_polished_primitives,
)
from generation_document_rendering_cases import (
    test_adaptive_layout_profile_infers_document_archetypes as test_adaptive_layout_profile_infers_document_archetypes,
)
from generation_document_rendering_cases import (
    test_deterministic_docx_uses_adaptive_style_system as test_deterministic_docx_uses_adaptive_style_system,
)
from generation_presentation_layout_cases import (
    test_deterministic_pptx_labels_timeline_profile as test_deterministic_pptx_labels_timeline_profile,
)
from generation_presentation_layout_cases import (
    test_deterministic_pptx_table_geometry_uses_content_shape as test_deterministic_pptx_table_geometry_uses_content_shape,
)
from generation_presentation_layout_cases import (
    test_deterministic_pptx_splits_tables_by_estimated_height as test_deterministic_pptx_splits_tables_by_estimated_height,
)
from generation_presentation_layout_cases import (
    test_deterministic_pptx_splits_large_lists_without_truncation as test_deterministic_pptx_splits_large_lists_without_truncation,
)
from generation_presentation_layout_cases import (
    test_deterministic_pptx_skips_generated_references_content_slide as test_deterministic_pptx_skips_generated_references_content_slide,
)
from generation_composition_cases import (
    test_normalizer_drops_generated_references_content_slide as test_normalizer_drops_generated_references_content_slide,
)
from generation_presentation_layout_cases import (
    test_deterministic_pptx_reports_slide_progress_without_changing_content as test_deterministic_pptx_reports_slide_progress_without_changing_content,
)
