"""Compatibility composition facade for administrator runtime configuration routes."""

from __future__ import annotations

from fastapi import APIRouter

from ...deployment import routes as _deployment_routes
from ...query import rag_config_http_mapping as _rag_config_http_mapping
from ...query import rag_config_routes as _rag_config_routes

router = APIRouter()
router.include_router(_rag_config_routes.router)
router.include_router(_deployment_routes.router)

# Keep direct imports stable while feature packages own the implementations.
get_workspace_rag_config = _rag_config_routes.get_workspace_rag_config
reset_workspace_rag_config = _rag_config_routes.reset_workspace_rag_config
list_workspace_reranker_models = _rag_config_routes.list_workspace_reranker_models
list_workspace_rag_models = _rag_config_routes.list_workspace_rag_models
test_workspace_rag_config = _rag_config_routes.test_workspace_rag_config
update_workspace_rag_config = _rag_config_routes.update_workspace_rag_config
get_vllm_deployment_config = _deployment_routes.get_vllm_deployment_config
update_vllm_deployment_config = _deployment_routes.update_vllm_deployment_config
apply_vllm_deployment_config = _deployment_routes.apply_vllm_deployment_config

_record_from_request = _rag_config_http_mapping._record_from_request
_record_from_discovery_request = _rag_config_http_mapping._record_from_discovery_request
_model_status_payload = _rag_config_http_mapping._model_status_payload
_base_url_from_host_port = _rag_config_http_mapping._base_url_from_host_port
_role_base_url = _rag_config_http_mapping._role_base_url
_provider = _rag_config_http_mapping._provider
_embedding_provider = _rag_config_http_mapping._embedding_provider
_role_provider = _rag_config_http_mapping._role_provider
_embedding_base_url = _rag_config_http_mapping._embedding_base_url
_embedding_matches_chat_provider = _rag_config_http_mapping._embedding_matches_chat_provider
_default_port = _rag_config_http_mapping._default_port
_provider_display = _rag_config_http_mapping._provider_display
_embedding_provider_display = _rag_config_http_mapping._embedding_provider_display
_rag_config_http_error = _rag_config_http_mapping._rag_config_http_error

_vllm_record_from_request = _deployment_routes._vllm_record_from_request
_service_limits_record = _deployment_routes._service_limits_record
_vllm_deployment_response = _deployment_routes._vllm_deployment_response
_service_limits_response = _deployment_routes._service_limits_response
