"""Compatibility facade for evidence-linked artifact composition."""

from __future__ import annotations

from .bundle_repair import (
    _block_has_payload,
    _collect_block_evidence_ids,
    _repair_blocks,
    _repair_key_value_block,
    _repair_list_block,
    _repair_section,
    _repair_table_block,
    _used_bundle_evidence_ids,
    fallback_repair_document_bundle,
    normalize_bundle_evidence_ids,
    repair_document_bundle,
)
from .composition import (
    COMPOSER_PROMPT_VERSION,
    COMPOSITION_RECORD_TEXT_LIMIT,
    MAX_RECORDS_PER_COMPOSITION_CALL,
    _compose_section,
    _compose_section_with_fallback,
    _dedupe_records,
    compose_document_bundle,
)
from .composition_deadline import _section_deadline
from .fallback_composition import (
    FALLBACK_MAX_LIST_ITEMS,
    FALLBACK_MAX_TABLE_COLUMNS,
    _clip,
    _evidence_or_status_summary,
    _fallback_bullet_section,
    _fallback_compact_record_table,
    _fallback_headers,
    _fallback_item_text,
    _fallback_section,
    _fallback_topic_header,
    _field_summary,
    _first_field_value,
    _first_matching_sentence,
    _is_useful_field,
    _key_detail_summary,
    _record_ids,
    _records_text,
    _should_use_compact_record_table,
    _subject_from_title,
    _topic_value,
)
from .format_adaptation import (
    FORMATTER_PROMPT_VERSION,
    MAX_BLOCKS_PER_SLIDE,
    MAX_PRESENTATION_SLIDES,
    REFERENCE_SLIDE_TITLES,
    _adapt_formats,
    _adapt_formats_deterministic,
    _adapt_formats_with_llm,
    _chunks,
    _is_generated_references_slide,
    _normalized_formats,
    _normalized_reference_title,
    _presentation_slides,
    _subtitle,
    _without_generated_references_slides,
)


__all__ = [
    "COMPOSER_PROMPT_VERSION",
    "COMPOSITION_RECORD_TEXT_LIMIT",
    "FALLBACK_MAX_LIST_ITEMS",
    "FALLBACK_MAX_TABLE_COLUMNS",
    "FORMATTER_PROMPT_VERSION",
    "MAX_BLOCKS_PER_SLIDE",
    "MAX_PRESENTATION_SLIDES",
    "MAX_RECORDS_PER_COMPOSITION_CALL",
    "REFERENCE_SLIDE_TITLES",
    "_adapt_formats",
    "_adapt_formats_deterministic",
    "_adapt_formats_with_llm",
    "_block_has_payload",
    "_chunks",
    "_clip",
    "_collect_block_evidence_ids",
    "_compose_section",
    "_compose_section_with_fallback",
    "_dedupe_records",
    "_evidence_or_status_summary",
    "_fallback_bullet_section",
    "_fallback_compact_record_table",
    "_fallback_headers",
    "_fallback_item_text",
    "_fallback_section",
    "_fallback_topic_header",
    "_field_summary",
    "_first_field_value",
    "_first_matching_sentence",
    "_is_generated_references_slide",
    "_is_useful_field",
    "_key_detail_summary",
    "_normalized_formats",
    "_normalized_reference_title",
    "_presentation_slides",
    "_record_ids",
    "_records_text",
    "_repair_blocks",
    "_repair_key_value_block",
    "_repair_list_block",
    "_repair_section",
    "_repair_table_block",
    "_section_deadline",
    "_should_use_compact_record_table",
    "_subject_from_title",
    "_subtitle",
    "_topic_value",
    "_used_bundle_evidence_ids",
    "_without_generated_references_slides",
    "compose_document_bundle",
    "fallback_repair_document_bundle",
    "normalize_bundle_evidence_ids",
    "repair_document_bundle",
]
