"""Build artifact-job contracts from a grounded RAG response."""

from __future__ import annotations

from hashlib import sha256
import re

from ..schemas.query import RAGResponse, SourceAnchor
from .contracts import (
    ArtifactContentBundle,
    ContentBlock,
    ContentSection,
    DocumentPlan,
    DocumentPlanSection,
    EvidenceBackedContent,
    EvidenceCitation,
    EvidenceManifest,
    EvidenceRecord,
    EvidenceSection,
    PaginatedDocumentSpec,
    PresentationSlide,
    PresentationSpec,
)


def response_is_artifact_ready(response: RAGResponse, *, faithfulness_threshold: float) -> bool:
    _ = faithfulness_threshold  # Kept for call-site compatibility.
    if not response.sources:
        return False
    if response.degraded and response.degraded_reason != "faithfulness_check_failed":
        return False
    return True


def build_grounded_artifact_payload(
    *,
    original_request: str,
    content_query: str,
    response: RAGResponse,
) -> tuple[DocumentPlan, EvidenceManifest, ArtifactContentBundle]:
    records = [_record_from_source(source, content_query=content_query) for source in _dedupe_sources(response.sources)]
    evidence_ids = [record.evidence_id for record in records]
    title = _title_from_query(content_query)
    section = ContentSection(
        title="Grounded answer",
        blocks=[
            ContentBlock(kind="paragraph", text=paragraph, evidence_ids=evidence_ids)
            for paragraph in _answer_paragraphs(response.answer)
        ] or [ContentBlock(kind="paragraph", text=response.answer.strip(), evidence_ids=evidence_ids)],
    )
    plan = DocumentPlan(
        title=title,
        purpose=f"Render the grounded answer for: {original_request}",
        document_type="report",
        assumptions=[
            "The content was generated by the normal RAG pipeline before file rendering.",
            "References are the source anchors selected for the displayed answer.",
        ],
        sections=[
            DocumentPlanSection(
                title=section.title,
                objective=f"Format the grounded answer for: {content_query}",
                preferred_blocks=["paragraph"],
                retrieval_queries=[content_query],
                retrieval_mode="focused_search",
                coverage_requirement="grounded_rag_response",
            )
        ],
    )
    evidence = EvidenceManifest(
        sections=[
            EvidenceSection(
                title=section.title,
                objective=f"Evidence selected by the normal RAG pipeline for: {content_query}",
                retrieval_mode="focused_search",
                coverage_requirement="grounded_rag_response",
                coverage_status="sufficient",
                records=records,
                warnings=["File content was rendered from the displayed grounded answer."],
                searched_query_count=1,
                top_k_record_count=len(records),
            )
        ]
    )
    citations = [
        EvidenceCitation(
            evidence_id=record.evidence_id,
            doc_id=record.doc_id,
            doc_title=record.doc_title,
            chunk_id=record.chunk_id,
            page_start=record.page_start,
            page_end=record.page_end,
        )
        for record in records
    ]
    content = EvidenceBackedContent(
        title=title,
        purpose=plan.purpose,
        sections=[section],
        citations=citations,
        warnings=["Rendered from the normal grounded RAG response."],
    )
    bundle = ArtifactContentBundle(
        content=content,
        paginated=PaginatedDocumentSpec(title=title, subtitle="Grounded RAG response", sections=[section]),
        presentation=PresentationSpec(
            title=title,
            subtitle="Grounded RAG response",
            slides=[PresentationSlide(title=section.title, blocks=section.blocks[:4])],
        ),
    )
    return plan, evidence, bundle


def _record_from_source(source: SourceAnchor, *, content_query: str) -> EvidenceRecord:
    return EvidenceRecord(
        evidence_id="ev_" + sha256(f"{source.doc_id}:{source.chunk_id}".encode("utf-8")).hexdigest()[:20],
        section_title="Grounded answer",
        query=content_query,
        doc_id=source.doc_id,
        doc_title=source.doc_title,
        chunk_id=source.chunk_id,
        page_start=source.page_start or source.page,
        page_end=source.page_end or source.page_start or source.page,
        content_type="source_anchor",
        text=source.excerpt,
    )


def _dedupe_sources(sources: list[SourceAnchor]) -> list[SourceAnchor]:
    seen: set[tuple[str, str]] = set()
    result: list[SourceAnchor] = []
    for source in sources:
        key = (source.doc_id, source.chunk_id)
        if key in seen:
            continue
        seen.add(key)
        result.append(source)
    return result


def _answer_paragraphs(answer: str) -> list[str]:
    return [part.strip() for part in re.split(r"\n{2,}", answer.strip()) if part.strip()]


def _title_from_query(query: str) -> str:
    words = [word for word in re.split(r"\s+", query.strip(" .")) if word]
    title = " ".join(word.upper() if word.isupper() else word.capitalize() for word in words[:12])
    return title[:180] or "Generated Document"
